modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="${mod_logo}"
authors="tablesouls"
description='''
Adds Elden ring/dark souls style titles for various events
'''

[[mixins]]
config="${mod_id}.mixins.json"

[[mixins]]
config="${mod_id}.mixins.bonfires.json"