jobs:
  build:
    permissions:
      contents: write
    steps:
      - uses: Kira-NT/mc-publish@v3
        with:
          modrinth-id: hx4Rlnhh
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 1602349
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
